package armory

// GlyphProperties.dbc IDs → English names (WotLK 3.3.5a build 12340).
// Unknown IDs fall back to "Glyph {id}".
var glyphNames = map[uint32]string{
	2:   "Glyph of Natural Force",
	21:  "Cruelty",
	22:  "Anticipation",
	61:  "Venomous Mana",
	81:  "Glyph of Natural Force",
	82:  "Glyph of Moonfire",
	121: "Copy of Holy Bolt",
	141: "Glyph of the White Bear",
	161: "Glyph of Frenzied Regeneration",
	162: "Glyph of Maul",
	163: "Glyph of Growling",
	164: "Glyph of Mangle",
	165: "Glyph of Shred",
	166: "Glyph of Rip",
	167: "Glyph of Rake",
	168: "Glyph of Swiftmend",
	169: "Glyph of Innervate",
	170: "Glyph of Rebirth",
	171: "Glyph of Regrowth",
	172: "Glyph of Rejuvenation",
	173: "Glyph of Healing Touch",
	174: "Glyph of Lifebloom",
	175: "Glyph of Starfire",
	176: "Glyph of Insect Swarm",
	177: "Glyph of Hurricane",
	178: "Glyph of Starfall",
	179: "Glyph of Wrath",
	180: "Glyph of Moonfire",
	181: "Glyph of Entangling Roots",
	182: "Glyph of the Red Lynx",
	183: "Glyph of Judgement",
	184: "Glyph of Seal of Command",
	185: "Glyph of Hammer of Justice",
	186: "Glyph of Spiritual Attunement",
	187: "Glyph of Hammer of Wrath",
	188: "Glyph of Crusader Strike",
	189: "Glyph of Consecration",
	190: "Glyph of Righteous Defense",
	191: "Glyph of Avenger's Shield",
	192: "Glyph of Turn Evil",
	193: "Glyph of Exorcism",
	194: "Glyph of Cleansing",
	195: "Glyph of Flash of Light",
	196: "Glyph of Holy Light",
	197: "Glyph of Avenging Wrath",
	198: "Glyph of Divinity",
	199: "Glyph of Seal of Wisdom",
	200: "Glyph of Seal of Light",
	211: "Glyph of Water Mastery",
	212: "Glyph of Chain Heal",
	213: "Glyph of Chain Lightning",
	214: "Glyph of Lava",
	215: "Glyph of Shocking",
	216: "Glyph of Earthliving Weapon",
	217: "Glyph of Fire Elemental Totem",
	218: "Glyph of Fire Nova",
	219: "Glyph of Flame Shock",
	220: "Glyph of Flametongue Weapon",
	221: "Glyph of Frost Shock",
	222: "Glyph of Healing Stream Totem",
	223: "Glyph of Healing Wave",
	224: "Glyph of Lesser Healing Wave",
	225: "Glyph of Lightning Shield",
	226: "Glyph of Lightning Bolt",
	227: "Glyph of Mana Tide",
	228: "Glyph of Stormstrike",
	229: "Glyph of Lava Lash",
	230: "Glyph of Elemental Mastery",
	231: "Glyph of Windfury Weapon",
	251: "Glyph of Circle of Healing",
	252: "Glyph of Dispel Magic",
	253: "Glyph of Fade",
	254: "Glyph of Fear Ward",
	255: "Glyph of Flash Heal",
	256: "Glyph of Holy Nova",
	257: "Glyph of Inner Fire",
	258: "Glyph of Lightwell",
	259: "Glyph of Mass Dispel",
	260: "Glyph of Mind Control",
	261: "Glyph of Shadow Word: Pain",
	262: "Glyph of Shadow",
	263: "Glyph of Power Word: Shield",
	264: "Glyph of Prayer of Healing",
	265: "Glyph of Psychic Scream",
	266: "Glyph of Renew",
	267: "Glyph of Scourge Imprisonment",
	268: "Glyph of Shadow Word: Death",
	269: "Glyph of Mind Flay",
	270: "Glyph of Smite",
	271: "Glyph of Spirit of Redemption",
	272: "Glyph of Incinerate",
	273: "Glyph of Conflagrate",
	274: "Glyph of Corruption",
	275: "Glyph of Curse of Agony",
	276: "Glyph of Death Coil",
	277: "Glyph of Fear",
	278: "Glyph of Felguard",
	279: "Glyph of Felhunter",
	280: "Glyph of Health Funnel",
	281: "Glyph of Healthstone",
	282: "Glyph of Howl of Terror",
	283: "Glyph of Immolate",
	284: "Glyph of Imp",
	285: "Glyph of Searing Pain",
	286: "Glyph of Shadow Bolt",
	287: "Glyph of Shadowburn",
	288: "Glyph of Siphon Life",
	289: "Glyph of Soulstone",
	290: "Glyph of Succubus",
	291: "Glyph of Unstable Affliction",
	292: "Glyph of Voidwalker",
	311: "Glyph of Arcane Explosion",
	312: "Glyph of Arcane Missiles",
	313: "Glyph of Arcane Power",
	314: "Glyph of Blink",
	315: "Glyph of Evocation",
	316: "Glyph of Fireball",
	317: "Glyph of Fire Blast",
	318: "Glyph of Frost Nova",
	319: "Glyph of Frostbolt",
	320: "Glyph of Ice Armor",
	321: "Glyph of Ice Block",
	322: "Glyph of Ice Lance",
	323: "Glyph of Icy Veins",
	324: "Glyph of Scorch",
	325: "Glyph of Invisibility",
	326: "Glyph of Mage Armor",
	327: "Glyph of Mana Gem",
	328: "Glyph of Molten Armor",
	329: "Glyph of Polymorph",
	330: "Glyph of Remove Curse",
	331: "Glyph of Water Elemental",
	351: "Glyph of Aimed Shot",
	352: "Glyph of Arcane Shot",
	353: "Glyph of the Beast",
	354: "Glyph of Mending",
	355: "Glyph of Aspect of the Viper",
	356: "Glyph of Bestial Wrath",
	357: "Glyph of Deterrence",
	358: "Glyph of Disengage",
	359: "Glyph of Freezing Trap",
	360: "Glyph of Frost Trap",
	361: "Glyph of Hunter's Mark",
	362: "Glyph of Immolation Trap",
	363: "Glyph of the Hawk",
	364: "Glyph of Multi-Shot",
	365: "Glyph of Rapid Fire",
	366: "Glyph of Serpent Sting",
	367: "Glyph of Snake Trap",
	368: "Glyph of Steady Shot",
	369: "Glyph of Trueshot Aura",
	370: "Glyph of Volley",
	371: "Glyph of Wyvern Sting",
	391: "Glyph of Adrenaline Rush",
	392: "Glyph of Ambush",
	393: "Glyph of Backstab",
	394: "Glyph of Blade Flurry",
	395: "Glyph of Crippling Poison",
	396: "Glyph of Deadly Throw",
	397: "Glyph of Evasion",
	398: "Glyph of Eviscerate",
	399: "Glyph of Expose Armor",
	400: "Glyph of Feint",
	401: "Glyph of Garrote",
	402: "Glyph of Ghostly Strike",
	403: "Glyph of Gouge",
	404: "Glyph of Hemorrhage",
	405: "Glyph of Preparation",
	406: "Glyph of Rupture",
	407: "Glyph of Sap",
	408: "Glyph of Vigor",
	409: "Glyph of Sinister Strike",
	410: "Glyph of Slice and Dice",
	411: "Glyph of Sprint",
	431: "Glyph of Aquatic Form",
	432: "Glyph of Challenging Roar",
	433: "Glyph of the Wild",
	434: "Glyph of Unburdened Rebirth",
	435: "Glyph of Thorns",
	436: "Glyph of the Forest Lynx",
	438: "Glyph of the Black Bear",
	439: "Glyph of Revive Pet",
	440: "Glyph of Mend Pet",
	441: "Glyph of Feign Death",
	442: "Glyph of Scare Beast",
	443: "Glyph of the Pack",
	444: "Glyph of Possessed Strength",
	445: "Glyph of Arcane Intellect",
	446: "Glyph of Fire Ward",
	447: "Glyph of Frost Ward",
	448: "Glyph of Frost Armor",
	449: "Glyph of the Bear Cub",
	450: "Glyph of the Penguin",
	451: "Glyph of Slow Fall",
	452: "Glyph of Blessing of Kings",
	453: "Glyph of Blessing of Might",
	454: "Glyph of Blessing of Wisdom",
	455: "Glyph of Lay on Hands",
	456: "Glyph of Sense Undead",
	457: "Glyph of the Wise",
	458: "Glyph of Fading",
	459: "Glyph of Levitate",
	460: "Glyph of Fortitude",
	461: "Glyph of Shackle Undead",
	462: "Glyph of Shadow Protection",
	463: "Glyph of Shadowfiend",
	464: "Glyph of Distract",
	465: "Glyph of Pick Lock",
	466: "Glyph of Pick Pocket",
	467: "Glyph of Safe Fall",
	468: "Glyph of Blurred Speed",
	469: "Glyph of Vanish",
	470: "Glyph of Astral Recall",
	471: "Glyph of the Arctic Wolf",
	472: "Glyph of the Black Wolf",
	473: "Glyph of Renewed Life",
	474: "Glyph of Water Breathing",
	475: "Glyph of Water Shield",
	476: "Glyph of Water Walking",
	477: "Glyph of Unending Breath",
	478: "Glyph of Drain Soul",
	479: "Glyph of Kilrogg",
	480: "Glyph of Curse of Exhausion",
	481: "Glyph of Enslave Demon",
	482: "Glyph of Souls",
	483: "Glyph of Battle",
	484: "Glyph of Bloodrage",
	485: "Glyph of Charge",
	486: "Glyph of Mocking Blow",
	487: "Glyph of Thunder Clap",
	488: "Glyph of Enduring Victory",
	489: "Glyph of Mortal Strike",
	490: "Glyph of Bloodthirst",
	491: "Glyph of Rapid Charge",
	492: "Glyph of Cleaving",
	493: "Glyph of Devastate",
	494: "Glyph of Execution",
	495: "Glyph of Hamstring",
	496: "Glyph of Heroic Strike",
	497: "Glyph of Intervene",
	498: "Glyph of Barbaric Insults",
	499: "Glyph of Overpower",
	500: "Glyph of Rending",
	501: "Glyph of Revenge",
	502: "Glyph of Blocking",
	503: "Glyph of Last Stand",
	504: "Glyph of Sunder Armor",
	505: "Glyph of Sweeping Strikes",
	506: "Glyph of Taunt",
	507: "Glyph of Resonating Power",
	508: "Glyph of Victory Rush",
	509: "Glyph of Whirlwind",
	511: "Glyph of Dark Command",
	512: "Glyph of Anti-Magic Shell",
	513: "Glyph of Heart Strike",
	514: "Glyph of Blood Tap",
	515: "Glyph of Bone Shield",
	516: "Glyph of Chains of Ice",
	518: "Glyph of Death's Embrace",
	519: "Glyph of Death Grip",
	520: "Glyph of Death and Decay",
	521: "Glyph of Frost Strike",
	522: "Glyph of Horn of Winter",
	523: "Glyph of Icebound Fortitude",
	524: "Glyph of Icy Touch",
	525: "Glyph of Obliterate",
	526: "Glyph of Plague Strike",
	527: "Glyph of the Ghoul",
	528: "Glyph of Rune Strike",
	529: "Glyph of Scourge Strike",
	530: "Glyph of Strangulate",
	531: "Glyph of Unbreakable Armor",
	532: "Glyph of Vampiric Blood",
	551: "Glyph of Dash",
	552: "Glyph of Ghost Wolf",
	553: "Glyph of Pestilence",
	554: "Glyph of Corpse Explosion",
	555: "Glyph of Raise Dead",
	556: "Glyph of Rune Tap",
	557: "Glyph of Blood Strike",
	558: "Glyph of Death Strike",
	559: "Glyph of Holy Wrath",
	560: "Glyph of Seal of Righteousness",
	561: "Glyph of Seal of Vengeance",
	571: "Glyph of Raise Dead",
	591: "Glyph of Frostfire",
	611: "Glyph of Blast Wave",
	612: "Glyph of Thunderstorm",
	613: "Glyph of Typhoon",
	631: "Glyph of Focus",
	651: "Glyph of Arcane Blast",
	671: "Glyph of Berserk",
	672: "Glyph of Wild Growth",
	673: "Glyph of Nourish",
	674: "Glyph of Savage Roar",
	675: "Glyph of Monsoon",
	676: "Glyph of Barkskin",
	677: "Glyph of Chimera Shot",
	691: "Glyph of Explosive Shot",
	692: "Glyph of Kill Shot",
	693: "Glyph of Explosive Trap",
	694: "Glyph of Scatter Shot",
	695: "Glyph of Raptor Strike",
	696: "Glyph of Deep Freeze",
	697: "Glyph of Living Bomb",
	698: "Glyph of Arcane Barrage",
	699: "Glyph of Mirror Image",
	700: "Glyph of Ice Barrier",
	701: "Glyph of Beacon of Light",
	702: "Glyph of Hammer of the Righteous",
	703: "Glyph of Divine Storm",
	704: "Glyph of Shield of Righteousness",
	705: "Glyph of Divine Plea",
	706: "Glyph of Holy Shock",
	707: "Glyph of Salvation",
	708: "Glyph of Dispersion",
	709: "Glyph of Guardian Spirit",
	710: "Glyph of Penance",
	711: "Glyph of Mind Sear",
	712: "Glyph of Hymn of Hope",
	713: "Glyph of Pain Suppression",
	714: "Glyph of Hunger For Blood",
	715: "Glyph of Killing Spree",
	716: "Glyph of Shadow Dance",
	731: "Glyph of Fan of Knives",
	732: "Glyph of Tricks of the Trade",
	733: "Glyph of Mutilate",
	734: "Glyph of Cloak of Shadows",
	735: "Glyph of Thunder",
	736: "Glyph of Feral Spirit",
	737: "Glyph of Riptide",
	751: "Glyph of Earth Shield",
	752: "Glyph of Totem of Wrath",
	753: "Glyph of Hex",
	754: "Glyph of Stoneclaw Totem",
	755: "Glyph of Haunt",
	756: "Glyph of Metamorphosis",
	757: "Glyph of Chaos Bolt",
	758: "Glyph of Demonic Circle",
	759: "Glyph of Shadowflame",
	760: "Glyph of Life Tap",
	761: "Glyph of Soul Link",
	762: "Glyph of Bladestorm",
	763: "Glyph of Shockwave",
	764: "Glyph of Vigilance",
	765: "Glyph of Enraged Regeneration",
	766: "Glyph of Spell Reflection",
	767: "Glyph of Shield Wall",
	768: "Glyph of Dancing Rune Weapon",
	769: "Glyph of Hungering Cold",
	770: "Glyph of Unholy Blight",
	771: "Glyph of Dark Death",
	772: "Glyph of Disease",
	773: "Glyph of Howling Blast",
	791: "Glyph of Envenom",
	811: "Glyph of Survival Instincts",
	831: "Glyph of Claw",
	851: "Glyph of Command",
	871: "Glyph of Eternal Water",
	891: "Glyph of Rapid Rejuvenation",
	911: "Glyph of Quick Decay",
}
