package armory

// GlyphProperties.dbc IDs → English names (WotLK 3.3.5a). Unknown IDs fall back to "Glyph {id}".
var glyphNames = map[uint32]string{
	183: "Glyph of Seal of Command",
	184: "Glyph of Hammer of Justice",
	185: "Glyph of Spiritual Attunement",
	186: "Glyph of Holy Light",
	187: "Glyph of Lay on Hands",
	188: "Glyph of Blessing of Might",
	189: "Glyph of Sense Undead",
	190: "Glyph of Consecration",
	191: "Glyph of Righteous Defense",
	192: "Glyph of Turn Evil",
	193: "Glyph of Exorcism",
	194: "Glyph of Cleansing",
	195: "Glyph of Flash of Light",
	196: "Glyph of Holy Wrath",
	197: "Glyph of Divinity",
	198: "Glyph of Seal of Wisdom",
	199: "Glyph of Seal of Light",
	200: "Glyph of Hammer of Wrath",
	201: "Glyph of Crusader Strike",
	202: "Glyph of Seal of Righteousness",
	203: "Glyph of Seal of Vengeance",
	204: "Glyph of Holy Shock",
	205: "Glyph of Avenger's Shield",
	206: "Glyph of Salvation",
	207: "Glyph of Shield of Righteousness",
	211: "Glyph of Divine Plea",
	212: "Glyph of Holy Wrath",
	213: "Glyph of Lay on Hands",
	411: "Glyph of Seal of Wisdom",
	// Common minor/other
	1:   "Glyph of Rapid Charge",
	2:   "Glyph of Rending",
	16:  "Glyph of Mortal Strike",
	556: "Glyph of Frost Strike",
	557: "Glyph of Dark Death",
	558: "Glyph of Icy Touch",
	559: "Glyph of Unholy Blight",
}
